create table tb_role (id int8 generated by default as identity, role varchar(255), primary key (id));
create table tb_user (id int8 generated by default as identity, user_email varchar(255), user_name varchar(255), user_password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table if exists tb_user add constraint UK_ky6rbh0axwmbamyg6wl4a7imb unique (user_email);
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
create table tb_employee (id int8 generated by default as identity, daily_income float8 check (daily_income>=0), employee_name varchar(255), primary key (id));
