INSERT INTO tb_user (USER_EMAIL, USER_NAME, USER_PASSWORD) VALUES ('blanny@email.com', 'Bruna', '$2a$10$mzDk6dI7Niu/xH/UlzBHIOPXiJq5X6W6rLBiyqLeEWxBusam7RMaO');
INSERT INTO tb_user (USER_EMAIL, USER_NAME, USER_PASSWORD) VALUES ('amanda@email.com', 'Amanda', '$2a$10$mzDk6dI7Niu/xH/UlzBHIOPXiJq5X6W6rLBiyqLeEWxBusam7RMaO');

INSERT INTO tb_role (ROLE) VALUES ('OPERATOR');
INSERT INTO tb_role (ROLE) VALUES ('ADMIN');

INSERT INTO tb_user_role (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO tb_user_role (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO tb_user_role (USER_ID, ROLE_ID) VALUES (2, 2);
